# Generated by Django 2.0.2 on 2018-02-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingwall',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='climbingwall',
            name='contacts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climbingwall',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climbingwall',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='climbingwall',
            name='open_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='climbingwall',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
