# Generated by Django 2.0.2 on 2018-02-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180208_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingwall',
            name='networks',
            field=models.ManyToManyField(blank=True, null=True, to='portal.SocialNetworkLink'),
        ),
    ]
