# Generated by Django 2.0.2 on 2018-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180208_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepicture',
            name='image',
            field=models.ImageField(null=True, upload_to='media/climbingwalls/'),
        ),
    ]
