# Generated by Django 2.0.2 on 2018-02-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/'),
        ),
    ]
