# Generated by Django 2.0.2 on 2018-03-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180212_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='climbing_wall',
            new_name='climbingwall',
        ),
    ]
