# Generated by Django 2.0.2 on 2018-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20180323_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepicture',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
