# Generated by Django 2.0.2 on 2018-03-24 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_routepicture_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingwallPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='media/climbingwalls/')),
                ('active', models.BooleanField(default=True)),
                ('climbingwall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='portal.ClimbingWall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='routepicture',
            name='image',
            field=models.ImageField(null=True, upload_to='media/routes/'),
        ),
    ]
