# Generated by Django 2.0.2 on 2018-04-12 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_competition_competitionparticipant_competitionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
