# Generated by Django 2.0.2 on 2018-04-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_competition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
