# Generated by Django 2.0.2 on 2018-04-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20180414_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='portal.Competition'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portal.CompetitionParticipant'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='result',
            field=models.CharField(choices=[('F', 'FLASH'), ('SG', 'SECOND GO'), ('RP', 'RED POINT')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='competitionresult',
            unique_together={('participant', 'route')},
        ),
    ]
